server:
  port: ${APP_PORT:5000}

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: customerService
          predicates:
            - Path=/api/customers/**
          uri: lb://${CUSTOMER_SERVICE_HOST:localhost}:8080/
#        - id: employeeService
#          predicates:
#            - Path=/api/employees/**
#          uri: lb://${EMPLOYEE_SERVICE_HOST:localhost}:8081/
#        - id: productService
#          predicates:
#            - Path=/api/products/**
#          uri: lb://${PRODUCT_SERVICE_HOST:localhost}:8082/

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka
  instance:
    hostname: localhost